export const Admission: any[] = [
    {
        admissionNumber: 1234567891,
        className: "full stack",
        admissionFree: 80000,
        section: "A",
        studentimg: "https://plus.unsplash.com/premium_photo-1664474619075-644dd191935f?q=80&w=2069&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        studentName: "RAHUL",
        dob: "2003-08-12",
        admissionDate: "2025-04-20",
        gender: "Male",
        category: "obc",
        studentMobile: "9570981841",
        address: "Patna",
        state: "Bihar",
        district: "Patna",
        pinCode: "800001",
        transport: "yes",
        fatherName: "Ram Kumar",
        motherName: "Sita Devi",
        localGardianName: "Ravi Kumar",
        parentAddress: "Patna City",
        parentNumber: "9999001000",
        relationStudents: "father",
        fatherOccupation: "teacher",
        withdrawalFileNumber: "2whg2b22bq12jhb344c",
        scholarRegistrationNo: "9090902324",
        lastSchoolName: "ABC Academy"
    },
    {
        admissionNumber: 1234567892,
        className: "full stack",
        admissionFree: 80000,
        section: "B",
        studentName: "PRIYA",
        dob: "2004-06-05",
        admissionDate: "2025-04-18",
        gender: "Female",
        category: "general",
        studentMobile: "9570981842",
        address: "Gaya",
        state: "Bihar",
        district: "Gaya",
        pinCode: "823001",
        transport: "yes",
        fatherName: "Suresh Kumar",
        motherName: "Meena Devi",
        localGardianName: "Amit Kumar",
        parentAddress: "Gaya Town",
        parentNumber: "9999001001",
        relationStudents: "father",
        fatherOccupation: "engineer",
        withdrawalFileNumber: "2whg2b22bq12jhb345d",
        scholarRegistrationNo: "9090902325",
        lastSchoolName: "XYZ High School"
    },
    {
        admissionNumber: 1234567893,
        className: "full stack",
        admissionFree: 80000,
        section: "A",
        studentName: "AMAN",
        dob: "2004-09-15",
        admissionDate: "2025-04-15",
        gender: "Male",
        category: "sc",
        studentMobile: "9570981843",
        address: "Muzaffarpur",
        state: "Bihar",
        district: "Muzaffarpur",
        pinCode: "842001",
        transport: "yes",
        fatherName: "Rajesh Kumar",
        motherName: "Sunita Devi",
        localGardianName: "Ajay Kumar",
        parentAddress: "Muzaffarpur City",
        parentNumber: "9999001002",
        relationStudents: "father",
        fatherOccupation: "businessman",
        withdrawalFileNumber: "2whg2b22bq12jhb346e",
        scholarRegistrationNo: "9090902326",
        lastSchoolName: "Sunrise School"
    },
    {
        admissionNumber: 1234567894,
        className: "full stack",
        admissionFree: 80000,
        section: "B",
        studentName: "ANKITA",
        dob: "2004-11-22",
        admissionDate: "2025-04-12",
        gender: "Female",
        category: "st",
        studentMobile: "9570981844",
        address: "Begusarai",
        state: "Bihar",
        district: "Begusarai",
        pinCode: "851101",
        transport: "no",
        fatherName: "Manoj Kumar",
        motherName: "Rekha Devi",
        localGardianName: "Anil Kumar",
        parentAddress: "Begusarai Town",
        parentNumber: "9999001003",
        relationStudents: "father",
        fatherOccupation: "farmer",
        withdrawalFileNumber: "2whg2b22bq12jhb347f",
        scholarRegistrationNo: "9090902327",
        lastSchoolName: "Modern School"
    },
    {
        admissionNumber: 1234567895,
        className: "full stack",
        admissionFree: 80000,
        section: "A",
        studentName: "VIKAS",
        dob: "2003-07-10",
        admissionDate: "2025-04-10",
        gender: "Male",
        category: "obc",
        studentMobile: "9570981845",
        address: "Darbhanga",
        state: "Bihar",
        district: "Darbhanga",
        pinCode: "846004",
        transport: "yes",
        fatherName: "Kamal Kishore",
        motherName: "Sarita Devi",
        localGardianName: "Pankaj Kumar",
        parentAddress: "Darbhanga City",
        parentNumber: "9999001004",
        relationStudents: "father",
        fatherOccupation: "shopkeeper",
        withdrawalFileNumber: "2whg2b22bq12jhb348g",
        scholarRegistrationNo: "9090902328",
        lastSchoolName: "Bright Future School"
    }
]

